#!/bin/sh
prg=$1
test -z "$prg" && prg=ff
forth=ff-amd64-OpenBSD
kernel=k-amd64-OpenBSD
nasm -f bin -dOpenBSD k-x86_64.s -o $kernel.bin -l $kernel.lst
awk -f lst2f.awk -v 'mbase=400200' $kernel.lst > words.f
od -An -t uC -v $kernel.bin | \
    awk '{for(i = 1; i <= NF; ++i) printf("%s c, ", $i); print ""}' > kernel.f
boot/$forth 'include tools.f' 'create target-OpenBSD' 'include mmf64.f' \
    "msave $forth" cr bye
./$forth 'include tools.f' 'include OpenBSD.f' 'include sys.f' "save $prg" cr bye
