#!/bin/sh
prg=$1
test -z "$prg" && prg=ff
forth=ff-ppc64le-Linux
gcc -DLinux '-Wa,-al=k-ppc64.lst' -c k-ppc64.s
objcopy -O binary k-ppc64.o k-ppc64.bin
gawk --posix -v 'mbase=400200' -f lst2fgnu.awk k-ppc64.lst > words.f
od -An -t uC -v k-ppc64.bin | \
    gawk '{for(i = 1; i <= NF; ++i) printf("%s c, ", $i); print ""}' > kernel.f
boot/$forth 'include tools.f' 'create target-Linux' \
    'create target-ppc64' 'include mmf64.f' "msave $forth" cr bye
./$forth 'include tools.f' 'include Linux.f' 'include sys.f' "save $prg" cr bye
