#!/bin/sh
prg=$1
test -z "$prg" && prg=ff
forth=ff-x86_64-Linux
kernel=k-x86_64-Linux
nasm -f bin -dLinux k-x86_64.s -o $kernel.bin -l $kernel.lst
gawk -f lst2f.awk -v 'mbase=400200' --posix $kernel.lst > words.f
od -An -t uC -v $kernel.bin | \
    gawk '{for(i = 1; i <= NF; ++i) printf("%s c, ", $i); print ""}' > kernel.f
boot/$forth 'include tools.f' 'create target-Linux' 'include mmf64.f' \
    "msave $forth" cr bye
./$forth 'include tools.f' 'include Linux.f' 'include sys.f' "save $prg" cr \
    bye
